# Generated by Django 2.1.2 on 2018-10-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('must_be', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('arrive', models.IntegerField(default=0)),
                ('need', models.IntegerField(default=0)),
            ],
        ),
    ]
